name: Tests

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v5
      - name: Setup .NET Core SDKs 
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            8.0.X
            9.0.X
            10.0.X
      - name: Install dependencies
        run: dotnet msbuild -target:restore .\build.proj
      - name: Build
        run: dotnet msbuild -target:solution .\build.proj
      - name: Unit Tests
        run: dotnet msbuild -target:unittests .\build.proj
      - name: Story Tests
        run: dotnet msbuild -target:storytests .\build.proj